Fix bash prompt overwrite

diff --git a/shell/bashrc b/shell/bashrc
--- a/shell/bashrc
+++ b/shell/bashrc
@@ -1,17 +1,75 @@
 set -o vi
 bind -m vi-insert "\C-l":clear-screen
 
-function colorized_prompt {
-   # Check if last command exit code equals 0
+NO_COLOR='\[\e[0m\]'
+WHITE='\[\e[1;37m\]'
+BLACK='\[\e[0;30m\]'
+BLUE='\[\e[0;34m\]'
+LIGHT_BLUE='\[\e[1;34m\]'
+GREEN='\e[0;32m'
+LIGHT_GREEN='\[\e[1;32m\]'
+CYAN='\[\e[0;36m\]'
+LIGHT_CYAN='\[\e[1;36m\]'
+RED='\[\e[0;31m\]'
+LIGHT_RED='\[\e[1;31m\]'
+PURPLE='\[\e[0;35m\]'
+LIGHT_PURPLE='\[\e[1;35m\]'
+BROWN='\[\e[0;33m\]'
+YELLOW='\[\e[1;33m\]'
+GRAY='\[\e[0;30m\]'
+LIGHT_GRAY='\[\e[0;37m\]'
+
+function _prompt_command() {
    local exit=$?
-   if (($exit)); then
-      printf "\e[31m╯°□°）╯︵ ┻━┻ ${exit}\e[m"
+
+   history -a
+
+   local NO_COLOR='\[\e[0m\]'
+   local WHITE='\[\e[1;37m\]'
+   local BLACK='\[\e[0;30m\]'
+   local BLUE='\[\e[0;34m\]'
+   local LIGHT_BLUE='\[\e[1;34m\]'
+   local GREEN='\[\e[0;32m\]'
+   local LIGHT_GREEN='\[\e[1;32m\]'
+   local CYAN='\[\e[0;36m\]'
+   local LIGHT_CYAN='\[\e[1;36m\]'
+   local RED='\[\e[0;31m\]'
+   local LIGHT_RED='\[\e[1;31m\]'
+   local PURPLE='\[\e[0;35m\]'
+   local LIGHT_PURPLE='\[\e[1;35m\]'
+   local BROWN='\[\e[0;33m\]'
+   local YELLOW='\[\e[1;33m\]'
+   local GRAY='\[\e[0;30m\]'
+   local LIGHT_GRAY='\[\e[0;37m\]'
+
+
+   PS_BASE="${NO_COLOR}\u@${GREEN}\w"
+   if (($exit))
+   then
+      PSX="$PS_BASE ${RED} ╯°□°）╯︵ ┻━┻ ${exit}"
    else
-      printf "\e[32m${exit}\e[m"
+      PSX="$PS_BASE ${GREEN}${exit}"
    fi
 
+   PS1="$PSX${NO_COLOR} \\$ "
 }
-export PS1='\[\e[37m\]\u\[\e[m\]@\[\e[32m\]\w\[\e[m\] $(colorized_prompt) '
+export PROMPT_COMMAND=_prompt_command
+
+
+function colorized_prompt() {
+   # Check if last command exit code equals 0
+   local exit=$?
+
+   if (($exit)); then
+      printf "${RED} ╯°□°）╯︵ ┻━┻ ${exit}"
+   else
+      printf "${GREEN}${exit}"
+   fi
+}
+# export PS1="${NO_COLOR}\u@${GREEN}\w${NO_COLOR} \$(colorized_prompt) \\$"
+# export PS1="\$(colorized_prompt) "
+# export PS1="${NO_COLOR}\u@${GREEN}\w${$NO_COLOR} $(colorized_prompt) \\$ "
+# export PS1='\[\e[37m\]\u\[\e[m\]@\[\e[32m\]\w\[\e[m\] $(colorized_prompt) '
 # export PS1='[\t] \W $(colorized_prompt) '
 # export PS1="\[\e[37m\]\u\[\e[m\]@\[\e[32m\]\w\[\e[m\]\\$ "
 
@@ -23,7 +81,7 @@ HISTSIZE=1000000
 HISTCONTROL=ignoreboth
 HISTIGNORE='ls:bg:fg:history'
 HISTTIMEFORMAT='%F %T '
-PROMPT_COMMAND='history -a'
+# PROMPT_COMMAND='history -a'
 
 
 export PATH=~/bin:$PATH
